import { useEffect, useState } from "react";
import { supabase } from "../../lib/supabase";

import Dashboard from "../dashboard/Dashboard";
import MyCloset from "../closet/MyCloset";
import AddClothes from "../closet/AddClothes";
import OutfitPlanner from "../outfit/OutfitPlanner";
import OutfitHistory from "../outfit/OutfitHistory";
import Favorites from "../favorites/Favorites";
import ProfileSettings from "../settings/ProfileSettings";

export interface ClothingItem {
  id: number;
  name: string;
  category: string;
  color: string;
  style: string;
  season: string;
  occasions: string[];
  image?: string;
  dateAdded: string;
  favorite: boolean;
}

type Page =
  | "Dashboard"
  | "My Closet"
  | "AI Stylist"
  | "Add Clothes"
  | "Outfit History"
  | "Favorites"
  | "Settings";

interface AppLayoutProps {
  onLogout: () => void;
}

function AppLayout({
  onLogout,
}: AppLayoutProps) {
  const [activePage, setActivePage] =
    useState<Page>("Dashboard");

  const [sidebarOpen, setSidebarOpen] =
    useState(false);

  const [clothingItems, setClothingItems] =
    useState<ClothingItem[]>([]);

  /*
   * Convert a Supabase clothing row
   * into the frontend ClothingItem format.
   */
  const formatClothingItem = (
    item: any
  ): ClothingItem => ({
    id: item.id,
    name: item.name,
    category: item.category,
    color: item.color,
    style: item.style,
    season: item.season,
    occasions: item.occasions ?? [],
    image:
      item.image_url ?? undefined,
    dateAdded: new Date(
      item.created_at
    ).toLocaleDateString(),
    favorite:
      item.favorite ?? false,
  });

  /*
   * Load clothing items belonging to
   * the currently authenticated user.
   */
  useEffect(() => {
    const loadClothingItems = async () => {
      try {
        const {
          data: { user },
        } = await supabase.auth.getUser();

        if (!user) {
          console.error(
            "No authenticated user found."
          );
          return;
        }

        const {
          data,
          error,
        } = await supabase
          .from("clothing_items")
          .select("*")
          .eq("user_id", user.id)
          .order("created_at", {
            ascending: false,
          });

        if (error) {
          console.error(
            "Failed to load clothing items:",
            error
          );
          return;
        }

        if (data) {
          const formattedItems =
            data.map(
              formatClothingItem
            );

          setClothingItems(
            formattedItems
          );
        }
      } catch (error) {
        console.error(
          "Unexpected error loading clothing items:",
          error
        );
      }
    };

    loadClothingItems();
  }, []);

  /*
   * Navigation
   */
  const handleNavigation = (
    page: Page
  ) => {
    setActivePage(page);
    setSidebarOpen(false);
  };

  /*
   * Add clothing
   *
   * AddClothes already uploads the image
   * and inserts the database row.
   *
   * Here we fetch the actual inserted row
   * so the frontend uses the REAL Supabase
   * ID instead of Date.now().
   */
  const handleAddClothing = async (
    item: Omit<
      ClothingItem,
      "id" | "dateAdded" | "favorite"
    >
  ) => {
    try {
      const {
        data: { user },
      } = await supabase.auth.getUser();

      if (!user) {
        console.error(
          "No authenticated user found."
        );
        return;
      }

      let query =
        supabase
          .from("clothing_items")
          .select("*")
          .eq("user_id", user.id);

      /*
       * image contains the Storage path
       * generated by AddClothes.
       *
       * Use it to find the exact row that
       * was just inserted.
       */
      if (item.image) {
        query = query.eq(
          "image_url",
          item.image
        );
      } else {
        query = query
          .eq("name", item.name)
          .order("created_at", {
            ascending: false,
          });
      }

      const {
        data,
        error,
      } = await query.limit(1).maybeSingle();

      if (error) {
        console.error(
          "Failed to fetch newly added clothing:",
          error
        );

        /*
         * Fallback: reload the complete
         * closet from Supabase.
         */
        await loadClothingItemsFromSupabase();

        setActivePage("My Closet");
        return;
      }

      if (data) {
        const newItem =
          formatClothingItem(data);

        setClothingItems(
          (currentItems) => [
            newItem,
            ...currentItems.filter(
              (existingItem) =>
                existingItem.id !==
                newItem.id
            ),
          ]
        );
      } else {
        /*
         * Fallback if the exact row
         * cannot be found.
         */
        await loadClothingItemsFromSupabase();
      }

      setActivePage("My Closet");
    } catch (error) {
      console.error(
        "Failed to add clothing to local state:",
        error
      );

      await loadClothingItemsFromSupabase();

      setActivePage("My Closet");
    }
  };

  /*
   * Reload the user's clothing directly
   * from Supabase.
   */
  const loadClothingItemsFromSupabase =
    async () => {
      try {
        const {
          data: { user },
        } = await supabase.auth.getUser();

        if (!user) {
          return;
        }

        const {
          data,
          error,
        } = await supabase
          .from("clothing_items")
          .select("*")
          .eq("user_id", user.id)
          .order("created_at", {
            ascending: false,
          });

        if (error) {
          console.error(
            "Failed to reload clothing items:",
            error
          );
          return;
        }

        if (data) {
          setClothingItems(
            data.map(
              formatClothingItem
            )
          );
        }
      } catch (error) {
        console.error(
          "Unexpected reload error:",
          error
        );
      }
    };

  /*
   * Delete clothing
   *
   * 1. Delete database row
   * 2. Delete image from Storage
   * 3. Update frontend
   */
  const handleDeleteClothing = async (
    id: number
  ) => {
    const item =
      clothingItems.find(
        (clothing) =>
          clothing.id === id
      );

    if (!item) {
      return;
    }

    try {
      /*
       * Delete database row first.
       */
      const {
        error: databaseError,
      } = await supabase
        .from("clothing_items")
        .delete()
        .eq("id", id);

      if (databaseError) {
        throw databaseError;
      }

      /*
       * Delete the corresponding image
       * from the private Storage bucket.
       */
      if (item.image) {
        const {
          error: storageError,
        } = await supabase.storage
          .from("clothing-images")
          .remove([item.image]);

        if (storageError) {
          console.error(
            "Storage image deletion warning:",
            storageError
          );
        }
      }

      /*
       * Remove the item from React state.
       */
      setClothingItems(
        (currentItems) =>
          currentItems.filter(
            (clothing) =>
              clothing.id !== id
          )
      );
    } catch (error) {
      console.error(
        "Failed to delete clothing item:",
        error
      );
    }
  };

  /*
   * Toggle favorite
   *
   * The change is persisted to Supabase,
   * so it survives page refreshes.
   */
  const handleToggleFavorite = async (
    id: number
  ) => {
    const item =
      clothingItems.find(
        (clothing) =>
          clothing.id === id
      );

    if (!item) {
      return;
    }

    const newFavorite =
      !item.favorite;

    try {
      const {
        error,
      } = await supabase
        .from("clothing_items")
        .update({
          favorite: newFavorite,
        })
        .eq("id", id);

      if (error) {
        throw error;
      }

      setClothingItems(
        (currentItems) =>
          currentItems.map(
            (clothing) =>
              clothing.id === id
                ? {
                    ...clothing,
                    favorite:
                      newFavorite,
                  }
                : clothing
          )
      );
    } catch (error) {
      console.error(
        "Failed to update favorite:",
        error
      );
    }
  };

  /*
   * Logout
   *
   * Sign out from Supabase first,
   * then return to the login screen.
   */
  const handleLogout = async () => {
    try {
      const {
        error,
      } = await supabase.auth.signOut();

      if (error) {
        throw error;
      }

      setClothingItems([]);
      setActivePage("Dashboard");

      onLogout();
    } catch (error) {
      console.error(
        "Failed to sign out:",
        error
      );
    }
  };

  /*
   * Render active page
   */
  const renderPage = () => {
    switch (activePage) {
      case "Dashboard":
        return <Dashboard />;

      case "My Closet":
        return (
          <MyCloset
            clothingItems={
              clothingItems
            }
            onAddClothes={() =>
              handleNavigation(
                "Add Clothes"
              )
            }
            onDeleteClothing={
              handleDeleteClothing
            }
            onToggleFavorite={
              handleToggleFavorite
            }
          />
        );

      case "AI Stylist":
        return <OutfitPlanner />;

      case "Add Clothes":
        return (
          <AddClothes
            onSave={
              handleAddClothing
            }
            onCancel={() =>
              handleNavigation(
                "My Closet"
              )
            }
          />
        );

      case "Outfit History":
        return <OutfitHistory />;

      case "Favorites":
        return <Favorites />;

      case "Settings":
        return <ProfileSettings />;

      default:
        return <Dashboard />;
    }
  };

  /*
   * Sidebar navigation
   */
  const navigation: {
    label: Page;
    icon: string;
  }[] = [
    {
      label: "Dashboard",
      icon: "⌂",
    },
    {
      label: "My Closet",
      icon: "▦",
    },
    {
      label: "AI Stylist",
      icon: "✦",
    },
    {
      label: "Add Clothes",
      icon: "+",
    },
    {
      label: "Outfit History",
      icon: "◷",
    },
    {
      label: "Favorites",
      icon: "♡",
    },
    {
      label: "Settings",
      icon: "⚙",
    },
  ];

  return (
    <div className="app-shell">

      {/* Mobile sidebar overlay */}

      {sidebarOpen && (
        <button
          className="sidebar-overlay"
          aria-label="Close navigation"
          onClick={() =>
            setSidebarOpen(false)
          }
        />
      )}

      {/* Sidebar */}

      <aside
        className={`app-sidebar ${
          sidebarOpen
            ? "mobile-open"
            : ""
        }`}
      >

        {/* Logo */}

        <div className="app-logo">

          <div className="app-logo-mark">
            ✦
          </div>

          <div>
            <strong>
              AI Closet
            </strong>

            <span>
              SMART WARDROBE
            </span>
          </div>

        </div>

        {/* Workspace */}

        <div className="sidebar-label">
          WORKSPACE
        </div>

        {/* Navigation */}

        <nav className="app-navigation">

          {navigation.map(
            (item) => (
              <button
                type="button"
                key={item.label}
                className={
                  activePage ===
                  item.label
                    ? "active"
                    : ""
                }
                onClick={() =>
                  handleNavigation(
                    item.label
                  )
                }
              >

                <span className="nav-icon">
                  {item.icon}
                </span>

                <span>
                  {item.label}
                </span>

                {item.label ===
                  "AI Stylist" && (
                  <span className="ai-nav-badge">
                    AI
                  </span>
                )}

              </button>
            )
          )}

        </nav>

        {/* AI Tip */}

        <div className="sidebar-ai-tip">

          <div className="sidebar-ai-icon">
            ✦
          </div>

          <span>
            AI STYLIST
          </span>

          <h3>
            Need an outfit?
          </h3>

          <p>
            Let AI create a look using
            your wardrobe and today's
            weather.
          </p>

          <button
            type="button"
            onClick={() =>
              handleNavigation(
                "AI Stylist"
              )
            }
          >
            Create outfit

            <span>
              →
            </span>
          </button>

        </div>

        {/* User area */}

        <div className="sidebar-user-area">

          <button
            type="button"
            className="sidebar-user"
            onClick={() =>
              handleNavigation(
                "Settings"
              )
            }
          >

            <div className="sidebar-avatar">
              P
            </div>

            <div>
              <strong>
                Pawan Krishna
              </strong>

              <span>
                Free Plan
              </span>
            </div>

            <span className="user-arrow">
              →
            </span>

          </button>

          {/* Logout */}

          <button
            type="button"
            className="sidebar-logout"
            onClick={
              handleLogout
            }
          >

            <span>
              ↪
            </span>

            Sign out

          </button>

        </div>

      </aside>

      {/* Main content */}

      <main className="app-main">

        {/* Topbar */}

        <header className="app-topbar">

          {/* Mobile menu */}

          <button
            type="button"
            className="mobile-menu-button"
            onClick={() =>
              setSidebarOpen(true)
            }
            aria-label="Open navigation"
          >
            ☰
          </button>

          {/* Breadcrumb */}

          <div className="breadcrumb">

            <span>
              AI Closet
            </span>

            <span>
              /
            </span>

            <strong>
              {activePage}
            </strong>

          </div>

          {/* Topbar actions */}

          <div className="topbar-actions">

            <button
              type="button"
              className="topbar-ai"
              onClick={() =>
                handleNavigation(
                  "AI Stylist"
                )
              }
            >

              <span>
                ✦
              </span>

              AI Stylist

            </button>

            <button
              type="button"
              className="topbar-avatar"
              onClick={() =>
                handleNavigation(
                  "Settings"
                )
              }
              aria-label="Open profile settings"
            >
              P
            </button>

          </div>

        </header>

        {/* Page */}

        <div className="app-page-content">
          {renderPage()}
        </div>

      </main>

    </div>
  );
}

export default AppLayout;